# Generated by Django 4.2.2 on 2023-07-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'homepage'},
        ),
    ]
